version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:20.04-5.7
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.7"

  test:
    image: swift-service-lifecycle:20.04-5.7
    environment:
      - SKIP_SIGNAL_TEST=true
      #- FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-service-lifecycle:20.04-5.7
