version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:18.04-5.3
    build:
      args:
        base_image: "swiftlang/swift:nightly-bionic"

  test:
    image: swift-service-lifecycle:18.04-5.3

  shell:
    image: swift-service-lifecycle:18.04-5.3
